name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create docker image
      run: make build-docker

    - name: Upload image
      run: |
        docker load < build/qemu-image
        docker tag qemu-image:latest ghcr.io/nicolaschan/stasis:latest
        docker push ghcr.io/nicolaschan/stasis:latest
